Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kconfig' : '@same'
    'frameworks/kcoreaddons' : '@same'
    'frameworks/kdbusaddons' : '@same'
    'frameworks/kiconthemes' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/knotifications' : '@same'
    'frameworks/kservice' : '@same'
    'frameworks/kwindowsystem' : '@same'
    'frameworks/kwidgetsaddons' : '@same'
    'libraries/qca': '@latest'
    'third-party/gpgme' : '@same'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
